export const menuItems = [
  {
    id: 1,
    label: "menuitems.menu.text",
    isTitle: true,
    role_id: [1, 10],
  },
  {
    id: 2,
    label: "menuitems.dashboards.text",
    icon: "bx-home-circle",
    link: "/dashboard",
    role_id: [1, 2, 7, 8, 9, 10],
  },
  {
    id: 3,
    label: "menuitems.bidang.text",
    icon: "bx-tone",
    link: "/bidang",
    role_id: [1],
  },
  {
    id: 4,
    label: "menuitems.ruangan.text",
    icon: "bx-home",
    link: "/ruangan",
    role_id: [1],
  },
  {
    id: 5,
    label: "menuitems.kepegawaian.text",
    icon: "bx-user",
    link: "/kepegawaian",
    role_id: [1],
  },
  // {
  //   id: 51,
  //   label: "menuitems.kepegawaian.text",
  //   icon: "bx-user",
  //   link: "/kepegawaian",
  //   role_id: [1],
  // },
  {
    id: 6,
    label: "menuitems.spesialiss.text",
    icon: "bx-grid-alt",
    link: "/spesialis",
    role_id: [1],
  },
  {
    id: 7,
    label: "menuitems.pendidikan.text",
    icon: "bx-grid-alt",
    link: "/pendidikan",
    role_id: [1],
  },
  {
    id: 8,
    label: "menuitems.jabatans.text",
    icon: "bx-grid-alt",
    link: "/jabatan",
    role_id: [1],
  },
  {
    id: 9,
    label: "menuitems.unit_kerja.text",
    icon: "bx-user-circle",
    link: "/unit-kerja",
    role_id: [1],
  },
  {
    id: 10,
    label: "History Aktifitas",
    icon: "bx-task",
    link: "/action-log",
    role_id: [1],
  },
  {
    id: 11,
    label: "Rekapitulasi Pegawai",
    icon: "bx-file",
    link: "/rekapitulasi-pegawai",
    role_id: [1],
  },
  {
    id: 12,
    label: "Profile Saya",
    icon: "bx-user",
    link: "/profile",
    role_id: [2, 7, 8, 9, 10],
  },
  {
    id: 13,
    label: "Management User",
    icon: "bx-user",
    link: "/user-data",
    role_id: [1],
  },
];
