<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterDokumenDigital;

class MasterDokumenDigitalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'file_nama' => 'Ijazah',
                'keterangan' => 'Upload Ijazah',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => 'riwayat_pendidikan',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 2,
                'file_nama' => 'Transkrip',
                'keterangan' => 'Upload Transkrip / Nilai',
                'is_wajib' => false,
                'order' => 2,
                'relation_to' => 'riwayat_pendidikan',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 3,
                'file_nama' => 'Izin Belajar',
                'keterangan' => 'Jika tingkat pendidikan berbeda saat pengangkatan pegawai pertama kali, wajib melampirkan ijin sekolah',
                'is_wajib' => false,
                'order' => 3,
                'relation_to' => 'riwayat_pendidikan',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 4,
                'file_nama' => 'SK Pengangkatan Jabatan',
                'keterangan' => 'Upload dokumen SK pengangkatan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'riwayat_jabatan',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 4,
                'file_nama' => 'SK Pengangkatan',
                'keterangan' => 'Upload dokumen SK pengangkatan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'riwayat_pengangkatan',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 5,
                'file_nama' => 'Daftar Riwayat Hidup',
                'keterangan' => 'Upload dokumen Daftar Riwayat Hidup',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 6,
                'file_nama' => 'SIP',
                'keterangan' => 'Upload dokumen SIP',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'sip',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 7,
                'file_nama' => 'STR',
                'keterangan' => 'Upload dokumen STR',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'str',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 8,
                'file_nama' => 'Paklaring',
                'keterangan' => 'Upload dokumen paklaring / surat keterangan bekerja',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'pengalaman_kerja',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 9,
                'file_nama' => 'Uraian Tugas',
                'keterangan' => 'Upload dokumen Uraian Tugas',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'uraian_tugas',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 10,
                'file_nama' => 'BPJS Kesehatan',
                'keterangan' => 'Upload dokumen BPJS Kesehatan',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 11,
                'file_nama' => 'BPJS Ketenagakerjaan',
                'keterangan' => 'Upload dokumen BPJS Ketenagakerjaan',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 12,
                'file_nama' => 'Foto Buku Rekening Depan',
                'keterangan' => 'Upload dokumen Foto Buku Rekening Depan',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 13,
                'file_nama' => 'Penilaian Kinerja',
                'keterangan' => 'Upload dokumen Penilaian Kinerja',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'penilaian_kinerja',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 14,
                'file_nama' => 'Kontrak',
                'keterangan' => 'Upload dokumen Kontrak',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'kontrak',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 17,
                'file_nama' => 'Riwayat Diklat Pelatihan',
                'keterangan' => 'Upload dokumen Riwayat Diklat Pelatihan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'riwayat_diklat',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 19,
                'file_nama' => 'NIRA',
                'keterangan' => 'Upload dokumen NIRA',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'nira',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 20,
                'file_nama' => 'Kartu Keluarga',
                'keterangan' => 'Upload dokumen Kartu Keluarga',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 21,
                'file_nama' => 'KTP',
                'keterangan' => 'Upload dokumen KTP',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 22,
                'file_nama' => 'Riwayat Asesmen',
                'keterangan' => 'Upload dokumen Riwayat Asesmen',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'riwayat_asesmen',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 23,
                'file_nama' => 'Portofolio',
                'keterangan' => 'Upload dokumen Portofolio',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 24,
                'file_nama' => 'Pas Photo',
                'keterangan' => 'Upload dokumen Pas Photo',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 25,
                'file_nama' => 'Riwayat Kesehatan',
                'keterangan' => 'Upload dokumen Riwayat Kesehatan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'riwayat_kesehatan',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 26,
                'file_nama' => 'Pelanggaran',
                'keterangan' => 'Upload dokumen Pelanggaran',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'pelanggaran',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 27,
                'file_nama' => 'Riwayat SK',
                'keterangan' => 'Upload dokumen Riwayat SK',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'riwayat_penempatan',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 28,
                'file_nama' => 'Riwayat RKK & SPKK PK',
                'keterangan' => 'Upload dokumen Riwayat RKK & SPKK PK',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'rkk_spkk_pk',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 29,
                'file_nama' => 'Status Pernikahan',
                'keterangan' => 'Upload dokumen Status Pernikahan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 32,
                'file_nama' => 'Akte Kelahiran',
                'keterangan' => 'Upload dokumen Akte Kelahiran',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'data_keluarga',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 33,
                'file_nama' => 'Akte Pernikahan',
                'keterangan' => 'Upload dokumen Akte Pernikahan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'data_keluarga',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 34,
                'file_nama' => 'Akte Cerai',
                'keterangan' => 'Upload dokumen Akte Cerai',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'data_keluarga',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 37,
                'file_nama' => 'Upload KTP',
                'keterangan' => 'Upload dokumen Foto KTP',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'data_keluarga',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 41,
                'file_nama' => 'Sertifikat Vaksin',
                'keterangan' => 'Upload dokumen Sertifikat Vaksin',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => 'riwayat_kesehatan_vaksin',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 42,
                'file_nama' => 'Upload Prestasi',
                'keterangan' => 'Upload dokumen Upload Prestasi',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'riwayat_prestasi',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 44,
                'file_nama' => 'Riwayat Tugas Tambahan',
                'keterangan' => 'Upload dokumen Riwayat Tugas Tambahan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'riwayat_tugas_tambahan',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 45,
                'file_nama' => 'Kenaikan Gaji Berkala',
                'keterangan' => 'Upload dokumen Kenaikan Gaji Berkala',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => 'riwayat_kenaikan_gaji_berkala',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 46,
                'file_nama' => 'Lamaran Kerja',
                'keterangan' => 'Upload dokumen Lamaran Kerja',
                'is_wajib' => true,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 43,
                'file_nama' => 'Status Pernikahan',
                'keterangan' => 'Upload dokumen Status Pernikahan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => 'data_keluarga',
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 48,
                'file_nama' => 'Tes Tulis',
                'keterangan' => 'Upload dokumen Tes Tulis',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 49,
                'file_nama' => 'Tes Wawancara',
                'keterangan' => 'Upload dokumen Tes Wawancara',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 50,
                'file_nama' => 'Tes Psikotes',
                'keterangan' => 'Upload dokumen Tes Psikotes',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 51,
                'file_nama' => 'Tes Kesehatan',
                'keterangan' => 'Upload dokumen Tes Kesehatan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 52,
                'file_nama' => 'Surat Kenaikan Golongan',
                'keterangan' => 'Upload dokumen Surat Kenaikan Golongan',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 53,
                'file_nama' => 'Riwayat MCU',
                'keterangan' => 'Upload dokumen Riwayat MCU',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => "riwayat_mcu",
                'logic_show' => null,
                'is_admin' => false,
            ],
            [
                'id' => 54,
                'file_nama' => 'Surat Keterangan Masih Sekolah',
                'keterangan' => 'Upload dokumen Surat Keterangan Masih Sekolah',
                'is_wajib' => false,
                'order' => 1,
                'relation_to' => null,
                'logic_show' => null,
                'is_admin' => false,
            ],
        ];

        foreach ($data as $key => $value) {
            MasterDokumenDigital::updateOrCreate([
                'id' => $value['id']
            ], [
                'file_nama' => $value['file_nama'],
                'keterangan' => $value['keterangan'],
                'is_wajib' => $value['is_wajib'],
                'order' => $value['order'],
                'relation_to' => $value['relation_to'],
                'logic_show' => $value['logic_show'],
                'is_admin' => $value['is_admin'],
            ]);
        }
    }
}
