version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9083:9083"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  nuxt:
    build: ./
    restart: always
    volumes:
      - ./:/src
    command:
      "/bin/sh -c 'npm install && npm run build && npm run start'"
