version: '3'
services:
  redis:
    restart: always
    image: redis:3.2-alpine
  app:
    build:
      context: .
      dockerfile: dockerconf/8.0/Dockerfile
    image: 127.0.0.1:5000/data-pegawai/laravel
    restart: always
    tty: true
    environment:
      CONTAINER_ROLE: app
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    ports:
      - "9084:8000"
    volumes:
      - ./:/var/www/html
      - ./nginx/local.ini:/usr/local/etc/php/conf.d/local.ini
  queue:
    build:
      context: .
      dockerfile: dockerconf/8.0/Dockerfile
    image: 127.0.0.1:5000/data-pegawai/laravel
    restart: always
    tty: true
    depends_on:
      - "app"
    environment:
      CONTAINER_ROLE: queue
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
  cron:
    build:
      context: .
      dockerfile: dockerconf/8.0/Dockerfile
    image: 127.0.0.1:5000/data-pegawai/laravel
    restart: always
    tty: true
    depends_on:
      - "app"
    environment:
      CONTAINER_ROLE: cron
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

